services:
  - type: web
    name: recipe-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTO_APPLY_EVOLUTIONS
        value: "true"
    # DATABASE_URL will be automatically provided by Render when you connect the database
    # Or manually add it in the Render Dashboard Environment settings
