services:
  - type: web
    name: recipe-api
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: recipe-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: recipe-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: recipe-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: recipe-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: recipe-db
          property: password
      - key: AUTO_APPLY_EVOLUTIONS
        value: "true"
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m

databases:
  - name: recipe-db
    databaseName: recipe_db
    user: recipe_user
